load("H:/benchmark0.01")
bench0.01 = times
load("H:/benchmark0.1")
bench0.1 = times
load("H:/benchmark0.2")
bench0.2 = times
load("H:/benchmark0.5")
bench0.5 = times


sizes = c(30, 100, 250, 500, 750, 1000, 2500)

#distance
benchmark.distance = function(x.vals = sizes){
  near = c(0.0001,0.001, 0.01, 0.1, 1, 10, 100, 1000)
  plot.new()
  plot.window(ylim = c(-9, 8), xlim = c(3.2,8))
  axis(1, at = log(x.vals), labels = x.vals)
  axis(2, at = log(near), labels = near)
  box()
  title(ylab = "Time (s)", xlab = "Network size (nodes)", main = "Distance Runtimes")
  points(x = log(x.vals), y = log(bench0.2$igraph.distance),  pch = 6, col = "red")
  points(x = log(x.vals), y = log(bench0.01$igraph.distance), pch = 6, col = "red")
  points(x = log(x.vals), y = log(bench0.1$igraph.distance),  pch = 6, col = "red")
  #points(x = log(x.vals), y = log(bench0.5$igraph.distance),  pch = 6, col = "red")
  lines( x = log(x.vals), y = log(bench0.01$igraph.distance), lty = 5, col = "red")
  lines( x = log(x.vals), y = log(bench0.1$igraph.distance),  lty = 5, col = "red")
  lines( x = log(x.vals), y = log(bench0.2$igraph.distance),  lty = 5, col = "red")
  #lines( x = log(x.vals), y = log(bench0.5$igraph.distance),  lty = 5, col = "red")
  
  points(x = log(x.vals), y = log(bench0.01$sna.distance),    pch = 1)
  points(x = log(x.vals), y = log(bench0.1$sna.distance),     pch = 1)
  points(x = log(x.vals), y = log(bench0.2$sna.distance),     pch = 1)
  #points(x = log(x.vals), y = log(bench0.5$sna.distance),    pch = 1)
  lines( x = log(x.vals), y = log(bench0.01$sna.distance),    lty = 5)
  lines( x = log(x.vals), y = log(bench0.1$sna.distance),     lty = 5)
  lines( x = log(x.vals), y = log(bench0.2$sna.distance),     lty = 5)
  #lines( x = log(x.vals), y = log(bench0.5$sna.distance),     lty = 5)
  
  legend("topleft", legend = c("igraph", "sna"), col = c("red", "black"), lty = c(5,5), pch = c(6,1), bty = "n")
}
pdf("benchmark_distance.pdf")
benchmark.distance()
dev.off()
#density
benchmark.density = function(x.vals = sizes){
  near = c(0.00005,0.0001,0.0002)
  plot.new()
  plot.window(ylim = c(-10, -8), xlim = c(3.2,8))
  axis(1, at = log(x.vals), labels = x.vals)
  axis(2, at = log(near), labels = near)
  box()
  title(ylab = "Time (s)", xlab = "Network size (nodes)", main = "Density Runtimes")
  points(x = log(x.vals), y = log(bench0.2$igraph.density),  pch = 6, col = "red")
  points(x = log(x.vals), y = log(bench0.01$igraph.density), pch = 6, col = "red")
  points(x = log(x.vals), y = log(bench0.1$igraph.density),  pch = 6, col = "red")
  #points(x = log(x.vals), y = log(bench0.5$igraph.density),  pch = 6, col = "red")
  lines( x = log(x.vals), y = log(bench0.01$igraph.density), lty = 5, col = "red")
  lines( x = log(x.vals), y = log(bench0.1$igraph.density),  lty = 5, col = "red")
  lines( x = log(x.vals), y = log(bench0.2$igraph.density),  lty = 5, col = "red")
  #lines( x = log(x.vals), y = log(bench0.5$igraph.density),  lty = 5, col = "red")
  
  points(x = log(x.vals), y = log(bench0.01$sna.density),    pch = 1)
  points(x = log(x.vals), y = log(bench0.1$sna.density),     pch = 1)
  points(x = log(x.vals), y = log(bench0.2$sna.density),     pch = 1)
  #points(x = log(x.vals), y = log(bench0.5$sna.density),     pch = 1)
  lines( x = log(x.vals), y = log(bench0.01$sna.density),    lty = 5)
  lines( x = log(x.vals), y = log(bench0.1$sna.density),     lty = 5)
  lines( x = log(x.vals), y = log(bench0.2$sna.density),     lty = 5)
  #lines( x = log(x.vals), y = log(bench0.5$sna.density),     lty = 5)
  
  legend("topleft", legend = c("igraph", "sna"), col = c("red", "black"), lty = c(5,5), pch = c(6,1), bty = "n")
}
pdf("benchmark_density.pdf")
benchmark.density()
dev.off()
#betweenness
benchmark.between = function(x.vals = sizes){
  near = c(0.0001,0.001, 0.01, 0.1, 1, 10, 100, 1000)
  plot.new()
  plot.window(ylim = c(-9, 8), xlim = c(3.2,8))
  axis(1, at = log(x.vals), labels = x.vals)
  axis(2, at = log(near), labels = near)
  box()
  title(ylab = "Log Time (log(s))", xlab = "Network size (nodes)", main = "Betweenness Centrality Runtimes")
  points(x = log(x.vals), y = log(bench0.2$igraph.between),  pch = 6, col = "red")
  points(x = log(x.vals), y = log(bench0.01$igraph.between), pch = 6, col = "red")
  points(x = log(x.vals), y = log(bench0.1$igraph.between),  pch = 6, col = "red")
  #points(x = log(x.vals), y = log(bench0.5$igraph.between),  pch = 6, col = "red")
  lines( x = log(x.vals), y = log(bench0.01$igraph.between), lty = 5, col = "red")
  lines( x = log(x.vals), y = log(bench0.1$igraph.between),  lty = 5, col = "red")
  lines( x = log(x.vals), y = log(bench0.2$igraph.between),  lty = 5, col = "red")
  #lines( x = log(x.vals), y = log(bench0.5$igraph.between),  lty = 5, col = "red")
  
  points(x = log(x.vals), y = log(bench0.01$sna.between),    pch = 1)
  points(x = log(x.vals), y = log(bench0.1$sna.between),     pch = 1)
  points(x = log(x.vals), y = log(bench0.2$sna.between),     pch = 1)
  #points(x = log(x.vals), y = log(bench0.5$sna.between),    pch = 1)
  lines( x = log(x.vals), y = log(bench0.01$sna.between),    lty = 5)
  lines( x = log(x.vals), y = log(bench0.1$sna.between),     lty = 5)
  lines( x = log(x.vals), y = log(bench0.2$sna.between),     lty = 5)
  #lines( x = log(x.vals), y = log(bench0.5$sna.between),     lty = 5)
  
  legend("topleft", legend = c("igraph", "sna"), col = c("red", "black"), lty = c(5,5), pch = c(6,1), bty = "n")
}
pdf("benchmark_betweenness.pdf")
benchmark.between()
dev.off()
#eigenvector
benchmark.eigen = function(x.vals = sizes){
  near = c(0.0001,0.001, 0.01, 0.1, 1, 10, 100, 1000)
  plot.new()
  plot.window(ylim = c(-9, 3), xlim = c(3.2,8))
  axis(1, at = log(x.vals), labels = x.vals)
  axis(2, at = log(near), labels = near)
  box()
  title(ylab = "Log Time (log(s))", xlab = "Network size (nodes)", main = "Eigenvector Centrality Runtimes")
  points(x = log(x.vals), y = log(bench0.2$igraph.eigen),  pch = 6, col = "red")
  points(x = log(x.vals), y = log(bench0.01$igraph.eigen), pch = 6, col = "red")
  points(x = log(x.vals), y = log(bench0.1$igraph.eigen),  pch = 6, col = "red")
  #points(x = log(x.vals), y = log(bench0.5$igraph.eigen),  pch = 6, col = "red")
  lines( x = log(x.vals), y = log(bench0.01$igraph.eigen), lty = 5, col = "red")
  lines( x = log(x.vals), y = log(bench0.1$igraph.eigen),  lty = 5, col = "red")
  lines( x = log(x.vals), y = log(bench0.2$igraph.eigen),  lty = 5, col = "red")
  #lines( x = log(x.vals), y = log(bench0.5$igraph.eigen),  lty = 5, col = "red")
  
  points(x = log(x.vals), y = log(bench0.01$sna.eigen),    pch = 1)
  points(x = log(x.vals), y = log(bench0.1$sna.eigen),     pch = 1)
  points(x = log(x.vals), y = log(bench0.2$sna.eigen),     pch = 1)
  #points(x = log(x.vals), y = log(bench0.5$sna.eigen),    pch = 1)
  lines( x = log(x.vals), y = log(bench0.01$sna.eigen),    lty = 5)
  lines( x = log(x.vals), y = log(bench0.1$sna.eigen),     lty = 5)
  lines( x = log(x.vals), y = log(bench0.2$sna.eigen),     lty = 5)
  #lines( x = log(x.vals), y = log(bench0.5$sna.eigen),     lty = 5)
  
  legend("topleft", legend = c("igraph", "sna"), col = c("red", "black"), lty = c(5,5), pch = c(6,1), bty = "n")
}
pdf("benchmark_eigen.pdf")
benchmark.eigen()
dev.off()

#Bonicich
benchmark.bon = function(x.vals = sizes){
  near = c(0.0001,0.001, 0.01, 0.1, 1, 10, 100, 1000)
  plot.new()
  plot.window(ylim = c(-11, 8), xlim = c(3.2,8))
  axis(1, at = log(x.vals), labels = x.vals)
  axis(2, at = log(near), labels = near)
  box()
  title(ylab = "Log Time (log(s))", xlab = "Network size (nodes)", main = "Bonicich Power Centrality Runtimes")
  points(x = log(x.vals), y = log(bench0.2$igraph.bon),  pch = 6, col = "red")
  points(x = log(x.vals), y = log(bench0.01$igraph.bon), pch = 6, col = "red")
  points(x = log(x.vals), y = log(bench0.1$igraph.bon),  pch = 6, col = "red")
  #points(x = log(x.vals), y = log(bench0.5$igraph.bon),  pch = 6, col = "red")
  lines( x = log(x.vals), y = log(bench0.01$igraph.bon), lty = 5, col = "red")
  lines( x = log(x.vals), y = log(bench0.1$igraph.bon),  lty = 5, col = "red")
  lines( x = log(x.vals), y = log(bench0.2$igraph.bon),  lty = 5, col = "red")
  #lines( x = log(x.vals), y = log(bench0.5$igraph.bon),  lty = 5, col = "red")
  
  points(x = log(x.vals), y = log(bench0.01$sna.bon),    pch = 1)
  points(x = log(x.vals), y = log(bench0.1$sna.bon),     pch = 1)
  points(x = log(x.vals), y = log(bench0.2$sna.bon),     pch = 1)
  #points(x = log(x.vals), y = log(bench0.5$sna.bon),    pch = 1)
  lines( x = log(x.vals), y = log(bench0.01$sna.bon),    lty = 5)
  lines( x = log(x.vals), y = log(bench0.1$sna.bon),     lty = 5)
  lines( x = log(x.vals), y = log(bench0.2$sna.bon),     lty = 5)
  #lines( x = log(x.vals), y = log(bench0.5$sna.bon),     lty = 5)
  
  legend("topleft", legend = c("igraph", "sna"), col = c("red", "black"), lty = c(5,5), pch = c(6,1), bty = "n")
}
pdf("benchmark_bon.pdf")
benchmark.bon()
dev.off()
#closeness
benchmark.close = function(x.vals = sizes){
  near = c(0.00005,0.001, 0.01, 0.1, 1, 10, 100, 1000)
  plot.new()
  plot.window(ylim = c(-10, 8), xlim = c(3.2,8))
  axis(1, at = log(x.vals), labels = x.vals)
  axis(2, at = log(near), labels = near)
  box()
  title(ylab = "Time (s)", xlab = "Network size (nodes)", main = "Closeness Centrality Runtimes")
  points(x = log(x.vals), y = log(bench0.2$igraph.close),  pch = 6, col = "red")
  points(x = log(x.vals), y = log(bench0.01$igraph.close), pch = 6, col = "red")
  points(x = log(x.vals), y = log(bench0.1$igraph.close),  pch = 6, col = "red")
  #points(x = log(x.vals), y = log(bench0.5$igraph.close),  pch = 6, col = "red")
  lines( x = log(x.vals), y = log(bench0.01$igraph.close), lty = 5, col = "red")
  lines( x = log(x.vals), y = log(bench0.1$igraph.close),  lty = 5, col = "red")
  lines( x = log(x.vals), y = log(bench0.2$igraph.close),  lty = 5, col = "red")
  #lines( x = log(x.vals), y = log(bench0.5$igraph.close),  lty = 5, col = "red")
  
  points(x = log(x.vals), y = log(bench0.01$sna.close),    pch = 1)
  points(x = log(x.vals), y = log(bench0.1$sna.close),     pch = 1)
  points(x = log(x.vals), y = log(bench0.2$sna.close),     pch = 1)
  #points(x = log(x.vals), y = log(bench0.5$sna.close),    pch = 1)
  lines( x = log(x.vals), y = log(bench0.01$sna.close),    lty = 5)
  lines( x = log(x.vals), y = log(bench0.1$sna.close),     lty = 5)
  lines( x = log(x.vals), y = log(bench0.2$sna.close),     lty = 5)
  #lines( x = log(x.vals), y = log(bench0.5$sna.close),     lty = 5)
  
  legend("topleft", legend = c("igraph", "sna"), col = c("red", "black"), lty = c(5,5), pch = c(6,1), bty = "n")
}
pdf("benchmark_closeness.pdf")
benchmark.close()
dev.off()

